[theme]
primaryColor = "#147D78"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#182B43"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
